### ISSUE TITLE
Breaking change i rapids-and-rivers

### ISSUE THREAD

**Issue by albrektsson** [navikt/k9-rapid#26]
https://github.com/navikt/rapids-and-rivers/commit/b37274a3439be473ad7c79d37aa04126f3a8b338

Rapids-and-rivers har endret til o bruke UUID.randomUUID() i JsonMessage som gør att hver gang en melding publiseres så er det med en ny, unik UUID. K9-Rapid bruker ULID som id och den brukes for att identifisere meldinger på tvers av applikasjoner.

**Comment by fraadsbrandth** [comment]
# Løsningsforslag
## Oppdatere k9-rapid

uten å oppdatere r&r-dependency

- [ ] Legge til en ny id `@behovssekvensId`
- [ ] Erstatte bruken av `@id` på ny behovssekvens med `@behovssekvensId`
- [ ] Oppdatere metode som henter ut behovssekvensId ved å hente `getOrNull("@behovssekvensId") ?: get("@id")` slik at vi henter fra nytt felt om det er satt og fallbacker til gammel
- [ ] Tilsvarende logikk som punktet over for løsning-resolver.

## Oppdatere k9-rapid-dependency tjenestene som bruker r&r

Må også sjekke om hver enkelt tjeneste fisker ut `@id` uten å bruke metode fra k9-rapid. Mistenker at f.eks. k9-vaktmester gjør det hvertfall

- [ ] k9-vaktmester
- [ ] k9-punsjbolle
- [ ] k9-personopplysninger
- [ ] omsorgspenger-journalforing
- [ ] omsorgspenger-sak
- [ ] omsorgspenger-rammemeldinger
- [ ] omsorgsdager

## Oppdatere producere som ikke bruker r&r

Slik at de begynner å sende behovssekvens med `@behovssekvensId` istedenfor `@id`

- [ ] k9-sak
- [ ] k9-punsj
- [ ] omsorgsdager-melding-prosessering
- [ ] Sjekke at det ikke er noen gamle meldinger i k9-vaktmester som kan bli republisert med `@id`

## Oppdatere k9-rapid del 2

- [ ] Fjerne alt som har med `@id` å gjøre - kun bruke `@behovssekvensId`
- [ ] Oppdatere r&r-dependency

## Oppdatere k9-rapid-dependency i tjeneste som bruker r&r

- [ ] k9-vaktmester
- [ ] k9-punsjbolle
- [ ] k9-personopplysninger
- [ ] omsorgspenger-journalforing
- [ ] omsorgspenger-sak
- [ ] omsorgspenger-rammemeldinger
- [ ] omsorgsdager

**Comment by albrektsson** [comment]
k9-punsj & sak har nye versjoner av k9-rapid i Q men ikke deployet i prod.
